name: "🪲 Report a bug"
description: Please describe the issue in detail
title: "bug: "
labels: ["needs review"]

body:
  - type: textarea
    id: problem-description
    attributes:
      label: Describe the Issue
      description: A clear and detailed description of what the issue is.
      placeholder: "Describe the issue..."
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: How can we duplicate it?
      description: "If known, how do you trigger this bug? Please walk us through it step by step."
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Describe the expected behavior.
      
  - type: input
    id: koboldcpp-version
    attributes:
      label: KoboldCpp Version
      description: What version of KoboldCpp are you using?
      placeholder: e.g., v1.2.3
      value: v
    validations:
      required: true
      
  - type: input
    id: operating-system
    attributes:
      label: Operating System(s)
      description: The operating system(s) you are using when you experience the problem.
      placeholder: e.g., Windows 10, macOS Big Sur, Ubuntu 20.04, Android
    validations:
      required: true
      
  - type: input
    id: cpu
    attributes:
      label: CPU
      description: CPU model?
      placeholder: e.g., Intel i7-9700K, AMD Ryzen 7 3700X

  - type: input
    id: gpu
    attributes:
      label: GPU
      description: GPU? (if any)
      placeholder: e.g., NVIDIA GeForce RTX 2080, AMD Radeon RX 5700 XT
      
  - type: textarea
    id: problem-description-additional
    attributes:
      label: Additional Information
      description: |
        Please provide any other relevant information about your setup.
        It would be helpful to include the launch params from the terminal output, flags and crash logs.
      placeholder: |
        launch parameters, snippet of the error, crash logs, etc.
