name: Create New Issue
description: Please describe the issue in detail
title: "bug: "
labels: ["needs review"]

body:
  - type: textarea
    id: problem-description
    attributes:
      label: Describe the Issue
      description: A clear and detailed description of what the issue is, and how to duplicate it (if applicable).
      placeholder: "Describe the issue..."
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: How can we duplicate it? (if known)
      description: "How do you trigger this bug? Please walk us through it step by step."
      value: |
        1.
        2.
        3.
        ...
      render: bash

  - type: textarea
    id: problem-description-additional
    attributes:
      label: Additional Information
      description: |
        Please provide as much relevant information about your setup as possible, such as the Operating System, CPU, GPU, KoboldCpp Version, and relevant logs.
        It would be helpful to include the launch params from the terminal output, flags and crash logs.
      placeholder: "Describe the issue..."
